--- #YAML:1.0
name:                Finance-SE-PPM
version:             0.04
abstract:            Retrieve a person's account status from the Swedish PPM
license:             ~
author:              
    - Erwan Lemonnier <erwlem@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Class::XPath:                  0
    Crypt::SSLeay:                 0
    HTML::TreeBuilder:             0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
